import { generateCard } from "../card.js";

/**
 * Minimal demo generator used by tests and local preview.
 * Returns an SVG string generated by the existing `generateCard` helper.
 */
export function generateDemoSvg(params = {}) {
    const demoStats = {
        mode: "daily",
        totalContributions: 2048,
        firstContribution: "2016-08-10",
        longestStreak: { start: "2021-12-19", end: "2022-03-14", length: 86 },
        currentStreak: { start: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10), end: new Date().toISOString().slice(0, 10), length: 3 },
        excludedDays: [],
    };

    try {
        return generateCard(demoStats, params);
    } catch (e) {
        // Fallback minimal SVG if generation fails
        const msg = e instanceof Error ? e.message : String(e);
        return `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="60"><text x="10" y="20">Demo error: ${msg}</text></svg>`;
    }
}

export default generateDemoSvg;
