<?php

// mapping of theme colors given a theme name
return [
    "default" => [
        "background" => "#FFFEFE",
        "border" => "#E4E2E2",
        "stroke" => "#E4E2E2",
        "ring" => "#FB8C00",
        "fire" => "#FB8C00",
        "currStreakNum" => "#151515",
        "sideNums" => "#151515",
        "currStreakLabel" => "#FB8C00",
        "sideLabels" => "#151515",
        "dates" => "#464646",
        "excludeDaysLabel" => "#464646",
    ],
    "dark" => [
        "background" => "#151515",
        "border" => "#E4E2E2",
        "stroke" => "#E4E2E2",
        "ring" => "#FB8C00",
        "fire" => "#FB8C00",
        "currStreakNum" => "#FEFEFE",
        "sideNums" => "#FEFEFE",
        "currStreakLabel" => "#FB8C00",
        "sideLabels" => "#FEFEFE",
        "dates" => "#9E9E9E",
        "excludeDaysLabel" => "#9E9E9E",
    ],
    "highcontrast" => [
        "background" => "#000000",
        "border" => "#BEBEBE",
        "stroke" => "#BEBEBE",
        "ring" => "#FB8C00",
        "fire" => "#FB8C00",
        "currStreakNum" => "#FFFFFF",
        "sideNums" => "#FFFFFF",
        "currStreakLabel" => "#FB8C00",
        "sideLabels" => "#FFFFFF",
        "dates" => "#C5C5C5",
        "excludeDaysLabel" => "#C5C5C5",
    ],
    "transparent" => [
        "background" => "#0000",
        "border" => "#E4E2E2",
        "stroke" => "#E4E2E2",
        "ring" => "#006AFF",
        "fire" => "#006AFF",
        "currStreakNum" => "#0579C3",
        "sideNums" => "#006AFF",
        "currStreakLabel" => "#0579C3",
        "sideLabels" => "#006AFF",
        "dates" => "#417E87",
        "excludeDaysLabel" => "#417E87",
    ],
    "radical" => [
        "background" => "#141321",
        "border" => "#E4E2E2",
        "stroke" => "#E4E2E2",
        "ring" => "#FE428E",
        "fire" => "#FE428E",
        "currStreakNum" => "#F8D847",
        "sideNums" => "#FE428E",
        "currStreakLabel" => "#F8D847",
        "sideLabels" => "#FE428E",
        "dates" => "#A9FEF7",
        "excludeDaysLabel" => "#A9FEF7",
    ],
    "watchdog" => [
        "background" => "45,520806,021D4A",
        "border" => "#E4E2E2",
        "stroke" => "#E4E2E2",
        "ring" => "#FE428E",
        "fire" => "#EB8C30",
        "currStreakNum" => "#F8D847",
        "sideNums" => "#FE428E",
        "currStreakLabel" => "#F8D847",
        "sideLabels" => "#FE428E",
        "dates" => "#A9FEF7",
        "excludeDaysLabel" => "#A9FEF7",
    ],
    "merko" => [
        "background" => "#0A0F0B",
        "border" => "#E4E2E2",
        "stroke" => "#E4E2E2",
        "ring" => "#ABD200",
        "fire" => "#ABD200",
        "currStreakNum" => "#B7D364",
        "sideNums" => "#ABD200",
        "currStreakLabel" => "#B7D364",
        "sideLabels" => "#ABD200",
        "dates" => "#68B587",
        "excludeDaysLabel" => "#68B587",
    ],
    "gruvbox" => [
        "background" => "#282828",
        "border" => "#E4E2E2",
        "stroke" => "#E4E2E2",
        "ring" => "#FABD2F",
        "fire" => "#FABD2F",
        "currStreakNum" => "#FE8019",
        "sideNums" => "#FABD2F",
        "currStreakLabel" => "#FE8019",
        "sideLabels" => "#FABD2F",
        "dates" => "#8EC07C",
        "excludeDaysLabel" => "#8EC07C",
    ],
    "gruvbox-duo" => [
        "background" => "#0000",
        "border" => "#A8A8A8",
        "stroke" => "#A8A8A8",
        "ring" => "#FABD2F",
        "fire" => "#FABD2F",
        "currStreakNum" => "#FE8019",
        "sideNums" => "#FABD2F",
        "currStreakLabel" => "#FE8019",
        "sideLabels" => "#FABD2F",
        "dates" => "#8EC07C",
        "excludeDaysLabel" => "#8EC07C",
    ],
    // ... (file continues, archived full content preserved)
];
